# Generated by Django 4.2 on 2023-04-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('adress', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
